// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1yHQeH7DsIS6PHX1Y-itxP8R393bGymc',
    appId: '1:709894121389:web:fdb4643f8c93e13b56e324',
    messagingSenderId: '709894121389',
    projectId: 'buang-bijak',
    authDomain: 'buang-bijak.firebaseapp.com',
    storageBucket: 'buang-bijak.firebasestorage.app',
    measurementId: 'G-H9D1L616M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwUS42L0rk0cc7X8csuxuwQAe7JgGZoA',
    appId: '1:709894121389:android:16e5d4f21ecbddbe56e324',
    messagingSenderId: '709894121389',
    projectId: 'buang-bijak',
    storageBucket: 'buang-bijak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpih13VwfHrKxFzK5r2ZrLsJKbN9M-4j4',
    appId: '1:709894121389:ios:c3e1015ca9016bfa56e324',
    messagingSenderId: '709894121389',
    projectId: 'buang-bijak',
    storageBucket: 'buang-bijak.firebasestorage.app',
    iosBundleId: 'com.example.fpTekber',
  );
}
